import { StyleSheet } from 'react-native';
import { COLORS, SPACING, TYPOGRAPHY, BORDERS, withOpacity } from '@/app/design-system/tokens';
import { platformShadow } from '@/app/design-system/tokens';

export const I = COLORS.institutional;
const FF = TYPOGRAPHY.fontFamily;

export const checklistItemStyles = StyleSheet.create({
  container: {
    backgroundColor: I.canvas,
    paddingVertical: SPACING.fixed.xs,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: SPACING.fixed.md,
  },
  headerLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.fixed.sm,
  },
  questionNumberBadge: {
    backgroundColor: withOpacity(I.primary, 0.1),
    borderRadius: BORDERS.radius.md,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: BORDERS.width.thin,
    borderColor: withOpacity(I.primary, 0.2),
  },
  questionNumber: {
    color: I.primary,
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansSemiBold,
  },
  questionContent: {
    flex: 1,
    minWidth: 0,
  },
  questionText: {
    fontSize: TYPOGRAPHY.fontSize.md,
    fontFamily: FF.sansSemiBold,
    color: I.ink,
    lineHeight: Math.round(TYPOGRAPHY.fontSize.md * TYPOGRAPHY.lineHeight.normal),
    marginBottom: SPACING.fixed.xxs,
  },
  helpText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansRegular,
    color: I.body,
    lineHeight: Math.round(TYPOGRAPHY.fontSize.sm * TYPOGRAPHY.lineHeight.normal),
  },
  requiredBadgeContainer: {
    width: 24,
    height: 24,
    borderRadius: BORDERS.radius.pill,
    backgroundColor: withOpacity(I.semanticDown, 0.08),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: BORDERS.width.thin,
    borderColor: withOpacity(I.semanticDown, 0.2),
  },
  inputContainer: {
    marginBottom: SPACING.fixed.md,
    gap: SPACING.fixed.sm,
  },
  modernTextInput: {
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    borderRadius: BORDERS.radius.lg,
    paddingHorizontal: SPACING.fixed.md,
    paddingVertical: SPACING.fixed.sm,
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansRegular,
    color: I.ink,
    backgroundColor: I.canvas,
  },
  singleLineTextInput: {
    minHeight: 44,
  },
  multilineTextInput: {
    minHeight: 96,
    paddingTop: SPACING.fixed.sm,
    textAlignVertical: 'top',
  },
  modernBooleanContainer: {
    flexDirection: 'row',
    gap: SPACING.fixed.sm,
  },
  modernBooleanButton: {
    flex: 1,
    paddingVertical: SPACING.fixed.sm,
    paddingHorizontal: SPACING.fixed.md,
    borderRadius: BORDERS.radius.lg,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    backgroundColor: I.canvas,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  modernBooleanButtonSelected: {
    backgroundColor: I.primary,
    borderColor: I.primary,
  },
  modernBooleanButtonText: {
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansMedium,
    color: I.muted,
  },
  modernBooleanButtonTextSelected: {
    color: I.onPrimary,
    fontFamily: FF.sansSemiBold,
  },
  modernSelectContainer: {
    gap: SPACING.fixed.xs,
  },
  modernOptionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.fixed.sm,
    paddingHorizontal: SPACING.fixed.md,
    borderRadius: BORDERS.radius.lg,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    backgroundColor: I.canvas,
    minHeight: 44,
  },
  modernOptionButtonSelected: {
    backgroundColor: I.primary,
    borderColor: I.primary,
  },
  optionCheckIcon: {
    marginRight: SPACING.fixed.sm,
  },
  modernOptionText: {
    flex: 1,
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansMedium,
    color: I.ink,
  },
  modernOptionTextSelected: {
    color: I.onPrimary,
    fontFamily: FF.sansSemiBold,
  },
  modernSelectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.fixed.sm,
    paddingHorizontal: SPACING.fixed.md,
    borderRadius: BORDERS.radius.lg,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    backgroundColor: I.surfaceSoft,
    minHeight: 44,
    justifyContent: 'space-between',
  },
  modernSelectButtonText: {
    flex: 1,
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansRegular,
    color: I.ink,
    marginLeft: SPACING.fixed.sm,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.fixed.xxs,
  },
  starButton: {
    padding: SPACING.fixed.xxs,
  },
  ratingText: {
    marginLeft: SPACING.fixed.sm,
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansMedium,
    color: I.ink,
  },
  modernPhotoContainer: {
    gap: SPACING.fixed.sm,
  },
  modernPhotoButtonsContainer: {
    flexDirection: 'row',
    gap: SPACING.fixed.sm,
  },
  modernPhotoButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.fixed.sm,
    paddingHorizontal: SPACING.fixed.md,
    borderRadius: BORDERS.radius.lg,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    backgroundColor: I.surfaceSoft,
    gap: SPACING.fixed.xs,
    minHeight: 44,
  },
  modernPhotoButtonDisabled: {
    opacity: 0.5,
  },
  modernPhotoButtonText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansSemiBold,
    color: I.primary,
  },
  uploadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.fixed.xs,
    paddingVertical: SPACING.fixed.sm,
    backgroundColor: withOpacity(I.primary, 0.06),
    borderRadius: BORDERS.radius.md,
  },
  uploadingText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansMedium,
    color: I.primary,
  },
  photoRequirementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.fixed.xxs,
  },
  photoRequirement: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansRegular,
    color: I.muted,
  },
  photoRequirementMet: {
    color: I.semanticUp,
    fontFamily: FF.sansMedium,
  },
  photoPreviewContainer: {
    gap: SPACING.fixed.xs,
  },
  photoPreviewTitle: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansSemiBold,
    color: I.ink,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.fixed.sm,
  },
  photoCard: {
    width: 96,
    gap: SPACING.fixed.xxs,
  },
  photoCardImageWrapper: {
    position: 'relative',
    width: 96,
    height: 96,
    borderRadius: BORDERS.radius.md,
    overflow: 'hidden',
    backgroundColor: I.surfaceSoft,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
  },
  photoCardImage: {
    width: '100%',
    height: '100%',
  },
  photoSyncBadge: {
    position: 'absolute',
    top: 4,
    left: 4,
    borderRadius: BORDERS.radius.sm,
    paddingHorizontal: 4,
    paddingVertical: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  photoSyncBadgeSynced: {
    backgroundColor: I.semanticUp,
  },
  photoSyncBadgePending: {
    backgroundColor: I.mutedSoft,
  },
  photoDeleteButton: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: I.semanticDown,
    borderRadius: BORDERS.radius.pill,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoCardDesc: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansMedium,
    color: I.body,
    lineHeight: 14,
  },
  descriptionModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: withOpacity(I.ink, 0.45),
  },
  descriptionModalSheet: {
    backgroundColor: I.canvas,
    borderTopLeftRadius: BORDERS.radius.xl,
    borderTopRightRadius: BORDERS.radius.xl,
    paddingHorizontal: SPACING.fixed.md,
    paddingTop: SPACING.fixed.sm,
    paddingBottom: SPACING.fixed.xl,
    gap: SPACING.fixed.sm,
  },
  descriptionModalHandle: {
    width: 36,
    height: 4,
    backgroundColor: I.hairline,
    borderRadius: BORDERS.radius.pill,
    alignSelf: 'center',
    marginBottom: SPACING.fixed.xxs,
  },
  descriptionModalTitle: {
    fontSize: TYPOGRAPHY.fontSize.md,
    fontFamily: FF.sansBold,
    color: I.ink,
    textAlign: 'center',
  },
  descriptionModalSubtitle: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansRegular,
    color: I.body,
    textAlign: 'center',
    lineHeight: Math.round(TYPOGRAPHY.fontSize.sm * TYPOGRAPHY.lineHeight.normal),
  },
  descriptionModalPreview: {
    width: '100%',
    height: 140,
    borderRadius: BORDERS.radius.lg,
    backgroundColor: I.surfaceSoft,
  },
  descriptionInput: {
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    borderRadius: BORDERS.radius.lg,
    paddingHorizontal: SPACING.fixed.md,
    paddingVertical: SPACING.fixed.sm,
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansRegular,
    color: I.ink,
    backgroundColor: I.surfaceSoft,
    marginTop: SPACING.fixed.xxs,
  },
  descriptionCharCount: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansRegular,
    color: I.mutedSoft,
    textAlign: 'right',
    marginTop: -4,
  },
  descriptionModalActions: {
    flexDirection: 'row',
    gap: SPACING.fixed.sm,
    marginTop: SPACING.fixed.xxs,
  },
  descriptionCancelButton: {
    flex: 1,
    paddingVertical: SPACING.fixed.sm,
    borderRadius: BORDERS.radius.pill,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  descriptionCancelText: {
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansSemiBold,
    color: I.muted,
  },
  descriptionConfirmButton: {
    flex: 2,
    paddingVertical: SPACING.fixed.sm,
    borderRadius: BORDERS.radius.pill,
    backgroundColor: I.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: SPACING.fixed.xs,
    minHeight: 44,
  },
  descriptionConfirmText: {
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansSemiBold,
    color: I.onPrimary,
  },
  numberInputWrapper: {
    gap: SPACING.fixed.xs,
  },
  rangeHint: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansRegular,
    color: I.muted,
    marginTop: SPACING.fixed.xxs,
  },
  modernSignatureContainer: {
    gap: SPACING.fixed.sm,
  },
  modernSignatureButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.fixed.sm,
    paddingHorizontal: SPACING.fixed.md,
    borderRadius: BORDERS.radius.lg,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    backgroundColor: I.canvas,
    gap: SPACING.fixed.xs,
    minHeight: 44,
  },
  modernSignatureButtonText: {
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansMedium,
    color: I.ink,
  },
  modernSignatureHelp: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansRegular,
    color: I.muted,
    paddingHorizontal: SPACING.fixed.xxs,
    lineHeight: 16,
  },
  modernSaveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.fixed.sm,
    paddingHorizontal: SPACING.fixed.lg,
    borderRadius: BORDERS.radius.pill,
    backgroundColor: I.primary,
    gap: SPACING.fixed.xs,
    marginTop: SPACING.fixed.sm,
    minHeight: 48,
    ...platformShadow({
      shadowColor: I.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 2,
    }),
  },
  modernSaveButtonDisabled: {
    backgroundColor: I.primaryDisabled,
    ...platformShadow({
      shadowColor: I.ink,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 3,
      elevation: 1,
    }),
  },
  modernSaveButtonText: {
    fontSize: TYPOGRAPHY.fontSize.base,
    fontFamily: FF.sansSemiBold,
    color: I.onPrimary,
  },
  completedIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.fixed.xs,
    paddingHorizontal: SPACING.fixed.md,
    gap: SPACING.fixed.xs,
    backgroundColor: withOpacity(I.semanticUp, 0.08),
    borderRadius: BORDERS.radius.lg,
    marginTop: SPACING.fixed.xs,
    borderWidth: BORDERS.width.thin,
    borderColor: withOpacity(I.semanticUp, 0.25),
  },
  completedText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansSemiBold,
    color: I.semanticUp,
  },
  notImplementedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.fixed.sm,
    paddingHorizontal: SPACING.fixed.md,
    borderRadius: BORDERS.radius.md,
    borderWidth: BORDERS.width.thin,
    borderColor: withOpacity(I.accentYellow, 0.45),
    backgroundColor: withOpacity(I.accentYellow, 0.08),
    gap: SPACING.fixed.xs,
  },
  notImplementedText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansMedium,
    color: I.body,
  },
  unsupportedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.fixed.sm,
    paddingHorizontal: SPACING.fixed.md,
    borderRadius: BORDERS.radius.md,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    backgroundColor: I.surfaceSoft,
    gap: SPACING.fixed.sm,
  },
  unsupportedText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansSemiBold,
    color: I.ink,
  },
  unsupportedSubtext: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansRegular,
    color: I.muted,
    marginTop: 2,
  },
});

export const SALUD_NIVEL_COLORS: Record<string, string> = {
  OPTIMO: I.semanticUp,
  ATENCION: I.accentYellow,
  URGENTE: COLORS.warning.dark,
  CRITICO: I.semanticDown,
};

export const SALUD_NIVEL_LABEL: Record<string, string> = {
  OPTIMO: 'Óptimo',
  ATENCION: 'Atención',
  URGENTE: 'Urgente',
  CRITICO: 'Crítico',
};

export const saludStyles = StyleSheet.create({
  container: {
    backgroundColor: I.surfaceSoft,
    borderRadius: BORDERS.radius.lg,
    padding: SPACING.fixed.sm,
    marginBottom: SPACING.fixed.sm,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.fixed.sm,
  },
  iconWrap: {
    width: 28,
    height: 28,
    borderRadius: BORDERS.radius.md,
    backgroundColor: I.surfaceStrong,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansSemiBold,
    color: I.ink,
  },
  intencionTag: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansRegular,
    color: I.muted,
    marginTop: 2,
  },
  badge: {
    paddingHorizontal: SPACING.fixed.xs,
    paddingVertical: 2,
    borderRadius: BORDERS.radius.sm,
  },
  badgeText: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansSemiBold,
    color: I.onPrimary,
  },
  metricsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: SPACING.fixed.sm,
    marginTop: SPACING.fixed.sm,
  },
  metric: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: I.canvas,
    borderRadius: BORDERS.radius.md,
    padding: SPACING.fixed.xs,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairlineSoft,
  },
  metricLabel: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansRegular,
    color: I.muted,
  },
  metricValue: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansSemiBold,
    color: I.ink,
    marginTop: 2,
  },
  barTrack: {
    height: 4,
    backgroundColor: I.hairlineSoft,
    borderRadius: BORDERS.radius.pill,
    overflow: 'hidden',
    marginTop: SPACING.fixed.xs,
  },
  barFill: {
    height: '100%',
    borderRadius: BORDERS.radius.pill,
  },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: SPACING.fixed.xxs,
  },
  metaText: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: FF.sansRegular,
    color: I.muted,
    marginRight: SPACING.fixed.xxs,
  },
});

export const sliderStyles = StyleSheet.create({
  container: {
    paddingHorizontal: SPACING.fixed.xxs,
    paddingTop: SPACING.fixed.xxs,
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: SPACING.fixed.xs,
  },
  valueText: {
    fontSize: TYPOGRAPHY.fontSize['2xl'],
    fontFamily: FF.sansBold,
  },
  nivelText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansSemiBold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  barTrack: {
    height: 6,
    borderRadius: BORDERS.radius.pill,
    backgroundColor: I.hairlineSoft,
    overflow: 'hidden',
    marginBottom: SPACING.fixed.sm,
  },
  barFill: {
    height: '100%',
    borderRadius: BORDERS.radius.pill,
  },
  stepRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: SPACING.fixed.xs,
    marginBottom: SPACING.fixed.sm,
  },
  stepButton: {
    flex: 1,
    paddingVertical: SPACING.fixed.xs,
    borderRadius: BORDERS.radius.md,
    backgroundColor: I.primary,
    alignItems: 'center',
    minHeight: 36,
    justifyContent: 'center',
  },
  stepButtonText: {
    color: I.onPrimary,
    fontFamily: FF.sansSemiBold,
    fontSize: TYPOGRAPHY.fontSize.sm,
  },
  presetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: SPACING.fixed.xxs,
  },
  presetButton: {
    flex: 1,
    paddingVertical: SPACING.fixed.xs,
    borderRadius: BORDERS.radius.md,
    borderWidth: BORDERS.width.thin,
    borderColor: I.hairline,
    backgroundColor: I.canvas,
    alignItems: 'center',
  },
  presetText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontFamily: FF.sansMedium,
    color: I.body,
  },
});
