/**
 * Puente de migración: nombres legacy (Material / Ionicons / MaterialCommunityIcons) → Lucide.
 * Preferir import directo desde `lucide-react-native` en código nuevo.
 */
import React, { memo } from 'react';
import type { LucideIcon, LucideProps } from 'lucide-react-native';
import {
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Award,
  BadgeCheck,
  Banknote,
  BanknoteX,
  Battery,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Bell,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarX,
  Camera,
  Car,
  ChartBar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleArrowRight,
  CircleCheck,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleQuestionMark,
  CircleX,
  ClipboardList,
  Clock,
  CloudCheck,
  CloudOff,
  CloudUpload,
  CreditCard,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  File,
  FileText,
  FileUp,
  Folder,
  Fuel,
  Gauge,
  Gift,
  Hand,
  HardHat,
  Home,
  Hourglass,
  Image,
  ImagePlus,
  Images,
  Inbox,
  Info,
  Landmark,
  Layers,
  LifeBuoy,
  Link,
  List,
  ListChecks,
  LocateFixed,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MapPinOff,
  MessageCircle,
  Minus,
  Package,
  Package2,
  Pause,
  Pencil,
  Phone,
  Play,
  Plus,
  Receipt,
  RefreshCw,
  Rocket,
  Save,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareCheck,
  SquareStop,
  Star,
  StickyNote,
  Store,
  Tag,
  Timer,
  TimerOff,
  Trash2,
  Truck,
  Undo2,
  Unlink,
  Upload,
  User,
  Wallet,
  Wifi,
  WifiOff,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react-native';
import { ICON_STROKE_WIDTH } from '@/app/design-system/iconography';

const LEGACY_MAP: Record<string, LucideIcon> = {
  info: Info,
  'info-outline': Info,
  warning: AlertTriangle,
  error: CircleAlert,
  'check-circle': CheckCircle,
  'account-balance-wallet': Wallet,
  payment: CreditCard,
  paid: CreditCard,
  build: Wrench,
  visibility: Eye,
  chat: MessageCircle,
  cancel: XCircle,
  schedule: CalendarClock,
  send: Send,
  undo: Undo2,
  'arrow-forward': ArrowRight,
  'error-outline': CircleAlert,
  'calendar-today': CalendarDays,
  event: CalendarDays,
  person: User,
  'directions-car': Car,
  car: Car,
  'location-on': MapPin,
  'location-off': MapPinOff,
  map: Map,
  'access-time': Clock,
  timer: Timer,
  verified: BadgeCheck,
  assignment: ClipboardList,
  'play-arrow': Play,
  'add-circle': CirclePlus,
  settings: Settings,
  'photo-library': Images,
  edit: Pencil,
  'delete-outline': Trash2,
  add: Plus,
  'add-circle-outline': CirclePlus,
  list: List,
  'table-chart': List,
  link: Link,
  'chevron-right': ChevronRight,
  sync: RefreshCw,
  'receipt-long': Receipt,
  remove: Minus,
  lock: Lock,
  'lock-outline': Lock,
  'lightning-bolt': Zap,
  'star-circle-outline': Star,
  'package-variant-closed': Package,
  'shield-check': ShieldCheck,
  'check-decagram': BadgeCheck,
  'clock-outline': Clock,
  'credit-card': CreditCard,
  'drive-eta': Car,
  store: Store,
  'insert-drive-file': FileText,
  'camera-alt': Camera,
  'my-location': LocateFixed,
  folder: Folder,
  star: Star,
  upload: Upload,
  'cloud-upload': CloudUpload,
  save: Save,
  'event-busy': CalendarX,
  'chevron-back': ChevronLeft,
  'chevron-forward': ChevronRight,
  inbox: Inbox,
  refresh: RefreshCw,
  'priority-high': AlertTriangle,
  'local-offer': Tag,
  'search-off': SearchX,
  'calendar-month': CalendarDays,
  speed: Gauge,
  tune: SlidersHorizontal,
  description: FileText,
  badge: Award,
  'build-circle': Factory,
  'local-shipping': Truck,
  'local-gas-station': Fuel,
  'add-photo-alternate': ImagePlus,
  search: Search,
  'search-outline': Search,
  'close-circle': CircleX,
  'construct-outline': Wrench,
  'car-sport-outline': Car,
  'albums-outline': Images,
  'information-circle-outline': Info,
  'camera-outline': Camera,
  'checkmark-done': ListChecks,
  'alert-circle-outline': CircleAlert,
  rocket: Rocket,
  'pause-circle': CirclePause,
  'play-circle': CirclePlay,
  engineering: HardHat,
  'ellipse-outline': Circle,
  checkbox: SquareCheck,
  'square-outline': Square,
  'expand-less': ChevronUp,
  'expand-more': ChevronDown,
  home: Home,
  'home-outline': Home,
  'battery-unknown': BatteryWarning,
  'eye-off-outline': EyeOff,
  'eye-outline': Eye,
  'radio-button-unchecked': Circle,
  'business-outline': Building2,
  'person-outline': User,
  'remove-circle-outline': CircleMinus,
  'cloud-done': CloudCheck,
  'cloud-off': CloudOff,
  wifi: Wifi,
  'wifi-off': WifiOff,
  'checkmark-circle-outline': CircleCheck,
  'alert-circle': CircleAlert,
  'help-circle': CircleQuestionMark,
  'help-circle-outline': CircleQuestionMark,
  clear: X,
  document: File,
  'document-text': FileText,
  'document-text-outline': FileText,
  layers: Layers,
  'inventory-2': Package2,
  'open-in-new': ExternalLink,
  payments: CreditCard,
  'pending-actions': Clock,
  receipt: Receipt,
  'attach-money': Banknote,
  'auto-fix-high': Sparkles,
  phone: Phone,
  call: Phone,
  email: Mail,
  mail: Mail,
  notifications: Bell,
  'notifications-outline': Bell,
  'offline-bolt': Zap,
  'add-shopping-cart': ShoppingCart,
  'shopping-cart': ShoppingCart,
  'card-giftcard': Gift,
  support: LifeBuoy,
  'information-outline': Info,
  'photo-camera': Camera,
  'upload-file': FileUp,
  'cloud-upload-outline': CloudUpload,
  logout: LogOut,
  'log-out-outline': LogOut,
  'timer-off': TimerOff,
  'refresh-outline': RefreshCw,
  'trash-outline': Trash2,
  trash: Trash2,
  delete: Trash2,
  location: MapPin,
  create: Pencil,
  'location-outline': MapPin,
  'stats-chart': ChartBar,
  'bar-chart': ChartBar,
  construct: Wrench,
  handyman: Wrench,
  'arrow-back': ArrowLeft,
  'arrow-drop-down': ChevronDown,
  'arrow-forward-circle': CircleArrowRight,
  'play-circle-filled': CirclePlay,
  'done-all': ListChecks,
  'car-sport': Car,
  card: CreditCard,
  'card-outline': CreditCard,
  storefront: Store,
  'build-outline': Wrench,
  check: Check,
  gesture: Hand,
  'link-off': Unlink,
  'shield-checkmark': ShieldCheck,
  'shield-checkmark-outline': Shield,
  'star-border': Star,
  image: Image,
  note: StickyNote,
  'swap-horiz': ArrowLeftRight,
  'account-balance': Landmark,
  'battery-0-bar': Battery,
  'battery-1-bar': BatteryLow,
  'battery-3-bar': BatteryMedium,
  'battery-5-bar': BatteryFull,
  'battery-full': BatteryFull,
  'money-off': BanknoteX,
  inventory: Package2,
  'more-horiz': Ellipsis,

  time: Clock,
  'chevron-down': ChevronDown,
  close: X,
  'checkmark-circle': CheckCircle,
  play: Play,
  stop: SquareStop,
  calendar: CalendarDays,
  pause: Pause,
  'information-circle': Info,
  business: Building2,
  checkmark: Check,
  security: Shield,
  'remove-circle': CircleMinus,
  pending: Clock,
  'hourglass-empty': Hourglass,
  help: CircleQuestionMark,
};

export type InstitutionalIconLegacyName = keyof typeof LEGACY_MAP;

export type InstitutionalIconProps = {
  /** Nombre usado antes con MaterialIcons / Ionicons / MaterialCommunityIcons */
  name: string;
  size: number;
  color: string;
  strokeWidth?: number;
} & Pick<LucideProps, 'accessibilityLabel' | 'style'>;

function InstitutionalIconInner({
  name,
  size,
  color,
  strokeWidth = ICON_STROKE_WIDTH,
  ...rest
}: InstitutionalIconProps) {
  const key = typeof name === 'string' ? name : String(name ?? '');
  const Cmp = LEGACY_MAP[key] ?? Info;
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} {...rest} />;
}

export const InstitutionalIcon = memo(InstitutionalIconInner);